// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtkcob80fkXcR8H-6RR6OPXc-dzelDIWM',
    appId: '1:205599538881:web:8f03b82037ea3e413f1e40',
    messagingSenderId: '205599538881',
    projectId: 'pr-5c180',
    authDomain: 'pr-5c180.firebaseapp.com',
    storageBucket: 'pr-5c180.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhfATAbyGKJIatLeCDlNuURQIU__9vPAI',
    appId: '1:205599538881:android:0e59d5154d7cbc4f3f1e40',
    messagingSenderId: '205599538881',
    projectId: 'pr-5c180',
    storageBucket: 'pr-5c180.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFdgZlTjZSYbIsCHKQ_fc1kHuS7nbMEi8',
    appId: '1:205599538881:ios:4a92707dfa1f62ce3f1e40',
    messagingSenderId: '205599538881',
    projectId: 'pr-5c180',
    storageBucket: 'pr-5c180.firebasestorage.app',
    iosBundleId: 'com.example.pr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFdgZlTjZSYbIsCHKQ_fc1kHuS7nbMEi8',
    appId: '1:205599538881:ios:4a92707dfa1f62ce3f1e40',
    messagingSenderId: '205599538881',
    projectId: 'pr-5c180',
    storageBucket: 'pr-5c180.firebasestorage.app',
    iosBundleId: 'com.example.pr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtkcob80fkXcR8H-6RR6OPXc-dzelDIWM',
    appId: '1:205599538881:web:e0c50eb37ed288ac3f1e40',
    messagingSenderId: '205599538881',
    projectId: 'pr-5c180',
    authDomain: 'pr-5c180.firebaseapp.com',
    storageBucket: 'pr-5c180.firebasestorage.app',
  );

}